name: auditory
description: Aureal

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.65+65



environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  amplitude_flutter: ^3.2.1
  clipboard: ^0.1.3
  cached_network_image: ^3.0.0
  font_awesome_flutter:
  flutter_ffmpeg:
  in_app_review: ^2.0.3
  loading_animations: "^2.1.0"
  loading_indicator: ^3.0.1
  audioplayer: ^0.8.1
  dio: ^5.1.1
  rflutter_alert: ^2.0.2
  percent_indicator: ^4.2.3
  dismissible_page: ^1.0.2
  linkable: ^3.0.1
  firebase_analytics: ^10.2.1
  modal_progress_hud: ^0.1.3
  datetime_picker_formfield: ^2.0.0
  provider: ^6.0.0
  file_picker: ^5.2.10
  autocomplete_textfield: ^2.0.1
  flutter_datetime_picker: ^1.3.8
  shimmer: ^2.0.0
  shared_preferences: ^2.0.7
  firebase_messaging: ^14.4.1
  flutter_swiper: ^1.1.6
  palette_generator: ^0.3.2
#  modal_bottom_sheet: ^2.0.0
  progress_dialog: ^1.2.4
  carousel_slider: ^4.0.0
  flutter_share: ^2.0.0
  transparent_image: ^2.0.0
  autocomplete_textfield_modified: ^1.6.11
  marquee: ^2.0.0
  timeago: ^3.0.2
  flutter_spinkit: ^5.0.0
  assets_audio_player: ^3.0.3+6
  koukicons: ^2.0.3
  line_icons: ^2.0.1
  image_picker: any
  image_cropper: any
  screenshot: any
  social_share: any
  share:  any
  scrollable_positioned_list: any
  animated_text_kit: ^4.2.1
  double_back_to_close_app: ^2.0.1
  webview_flutter: ^4.2.0
  url_launcher: ^6.0.3
  flutter_html: ^3.0.0-alpha.6
  image: ^4.0.15
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.0
  pin_code_fields: ^7.0.0
  async: ^2.4.2
  fluttertoast: ^8.0.3
  color_thief_flutter: ^1.0.2
  sqflite: ^2.0.0+3
  flutter_local_notifications: ^8.1.1+1
  dotted_border: ^2.0.0-nullsafety.0
  intl: ^0.18.1
  permission_handler: ^10.2.0
  flutter_inappwebview: ^5.3.2
  add_2_calendar: ^2.1.1
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  flutter_signin_button: ^2.0.0
  flutter_downloader: ^1.5.2
  form_field_validator: ^1.0.1
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  hive: ^2.0.4
  http: ^0.13.0
  lottie: ^2.3.2
  expandable: ^5.0.1
  sign_in_with_apple: ^4.3.0
  page_transition: ^2.0.2
  path_provider: any
  uni_links: ^0.5.0
  badges: ^3.1.1
  jitsi_meet: ^4.0.0
  flutter_vibrate: ^1.3.0
  mime: ^1.0.1
  chewie: ^1.3.0
  video_player: ^2.3.0
  flutter_sticky_header: ^0.6.1
  miniplayer: ^1.0.1


dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
#  local_auth: ^0.6.3+4

flutter_icons:
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/google.png
    - assets/images/Favicon.png
    - assets/images/AlbumArt.jpg
    - assets/images/catAlbumArt.png
    - assets/images/person.png
    - assets/images/startNow.png
    - assets/images/search.png
    - assets/images/CreatePodcast.png
    - assets/images/Thumbnail.png
    - assets/images/user.png
    - assets/images/internetIssue.png
    - assets/images/hive-login.png
    - assets/images/animatedtick.gif
    - assets/images/empty.svg
    - assets/images/loading.gif
    - assets/images/
    - assets/fonts/selectedIcon.ttf
    - assets/test_service_account.json
    - assets/audio/test.wav



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Avenir
       fonts:
         - asset: assets/fonts/Avenir-Light.ttf
         - asset: assets/fonts/Avenir-Medium.ttf



  #         style: italic

     - family: Metropolis
       fonts:
         - asset: assets/fonts/Metropolis/Metropolis-Black.ttf
           weight: 900
         - asset: assets/fonts/Metropolis/Metropolis-BlackItalic.ttf
           weight: 900
         - asset: assets/fonts/Metropolis/Metropolis-Bold.ttf
           weight: 700
         - asset: assets/fonts/Metropolis/Metropolis-BoldItalic.ttf
           weight: 700
         - asset: assets/fonts/Metropolis/Metropolis-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Metropolis/Metropolis-ExtraBoldItalic.ttf
           weight: 800
         - asset: assets/fonts/Metropolis/Metropolis-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Metropolis/Metropolis-ExtraLightItalic.ttf
           weight: 200
#         - asset: assets/fonts/Metropolis/Metropolis-Italic.ttf
#           weight: 400
#         - asset: assets/fonts/Metropolis/Metropolis-Light.ttf
#           weight: 300
         - asset: assets/fonts/Metropolis/Metropolis-LightItalic.ttf
           weight: 300
         - asset: assets/fonts/Metropolis/Metropolis-Regular.ttf
           weight: 400
         - asset: assets/fonts/Metropolis/Metropolis-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Metropolis/Metropolis-SemiBoldItalic.ttf
           weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
